/* ================================================================
 * AI 厂商福利情报站 · 数据文件（由人工与 scripts/update-data.mjs 共同维护）
 * 自动收录的条目带 "auto": true，人工核对无误后请删掉该标记。
 * ================================================================ */
window.DATA = {
  "updatedAt": "2026-09-01",
  "eggs": [
    {
      "vendor": "智谱 AI",
      "color": "#4f6ef7",
      "title": "新用户注册礼",
      "desc": "注册即送 2000 万 Tokens，GLM 全系模型通用，标注为永久额度",
      "amount": "2000 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 2000,
      "forever": true,
      "end": null,
      "url": "https://open.bigmodel.cn"
    },
    {
      "vendor": "智谱 AI",
      "color": "#4f6ef7",
      "title": "GLM-Flash 系列",
      "desc": "GLM-4-Flash / 4.7-Flash 开放平台永久免费，仅限并发数",
      "amount": "0 元",
      "unit": "长期免费",
      "type": "forever",
      "value": 2400,
      "forever": true,
      "end": null,
      "url": "https://open.bigmodel.cn"
    },
    {
      "vendor": "硅基流动",
      "color": "#7c5cff",
      "title": "新用户注册礼",
      "desc": "注册送 2000 万 Tokens 永久额度，平台聚合 DeepSeek / Qwen / GLM 等热门开源模型",
      "amount": "2000 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 2000,
      "forever": true,
      "end": null,
      "url": "https://siliconflow.cn"
    },
    {
      "vendor": "阿里云百炼",
      "color": "#ff6a00",
      "title": "新客全家桶",
      "desc": "新用户每个模型 100 万 Tokens，覆盖 Qwen / DeepSeek / Kimi 等 100+ 模型",
      "amount": "100 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 800,
      "end": "2026-11-30",
      "url": "https://bailian.console.aliyun.com"
    },
    {
      "vendor": "火山方舟",
      "color": "#3b82f6",
      "title": "协作奖励计划",
      "desc": "加入计划后每天可领 200 万 Tokens，长期有效，豆包 / DeepSeek / Qwen 全系可用",
      "amount": "200 万",
      "unit": "每天",
      "type": "daily",
      "value": 1200,
      "forever": true,
      "end": null,
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "vendor": "火山方舟",
      "color": "#3b82f6",
      "title": "新模型体验额度",
      "desc": "每个模型免费 50 万 tokens 体验金，安心体验模式下不计费",
      "amount": "50 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 300,
      "end": "2026-11-15",
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "vendor": "DeepSeek",
      "color": "#4d6bfe",
      "title": "V3.2 上线限时 5 折",
      "desc": "新版本 API 限时半价，输入 ¥1 / 输出 ¥1.5 每百万 tokens",
      "amount": "5 折",
      "unit": "API 折扣",
      "type": "limited",
      "value": 600,
      "end": "2026-09-03",
      "url": "https://platform.deepseek.com"
    },
    {
      "vendor": "腾讯云混元",
      "color": "#0052d9",
      "title": "新客体验金",
      "desc": "新用户 100 万 Tokens，有效期一年，混元全系模型可用",
      "amount": "100 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 100,
      "end": "2026-12-31",
      "url": "https://cloud.tencent.com/product/hunyuan"
    },
    {
      "vendor": "百度千帆",
      "color": "#2932e1",
      "title": "新客模型体验金",
      "desc": "每个模型 100 万 Tokens 免费额度，ERNIE 系列与开源模型均可体验",
      "amount": "100 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 100,
      "end": "2026-10-31",
      "url": "https://cloud.baidu.com/product/qianfan"
    },
    {
      "vendor": "Moonshot Kimi",
      "color": "#000000",
      "title": "开放平台新客券",
      "desc": "注册送 15 元体验金，K2 系列模型 API 通用，可抵扣按量费用",
      "amount": "¥15",
      "unit": "代金券",
      "type": "signup",
      "value": 400,
      "end": "2026-09-15",
      "url": "https://platform.moonshot.cn"
    },
    {
      "vendor": "MiniMax",
      "color": "#f23f5d",
      "title": "新客代金券包",
      "desc": "注册送 15 元代金券，M2 系列 API 通用，另有免费体验模型",
      "amount": "¥15",
      "unit": "代金券",
      "type": "signup",
      "value": 400,
      "end": "2026-09-30",
      "url": "https://www.minimaxi.com"
    },
    {
      "vendor": "Google Gemini",
      "color": "#1a73e8",
      "title": "API 免费层",
      "desc": "Flash 系列免费层每分钟 / 每日均有免费请求配额，个人开发够用",
      "amount": "免费层",
      "unit": "每日配额",
      "type": "forever",
      "value": 1500,
      "forever": true,
      "end": null,
      "url": "https://aistudio.google.com"
    },
    {
      "vendor": "OpenRouter",
      "color": "#a3a3a3",
      "title": ":free 模型通道",
      "desc": "带 :free 后缀的模型每日 50 次免费请求，聚合多家厂商的免费版本",
      "amount": "50 次",
      "unit": "每天",
      "type": "daily",
      "value": 200,
      "forever": true,
      "end": null,
      "url": "https://openrouter.ai"
    },
    {
      "vendor": "Groq",
      "color": "#f55036",
      "title": "免费层极速推理",
      "desc": "开源模型免费层每日可用，LPU 推理速度极快，适合大批量轻任务",
      "amount": "每日",
      "unit": "免费配额",
      "type": "daily",
      "value": 150,
      "forever": true,
      "end": null,
      "url": "https://console.groq.com"
    }
  ],
  "free": [
    {
      "name": "GLM-Flash 系列",
      "vendor": "智谱 AI",
      "cat": "api",
      "region": "cn",
      "desc": "GLM-4.7-Flash / 4-Flash 永久免费 API",
      "limits": "并发数限制，高峰期限速，无 SLA",
      "card": false,
      "cardNote": "",
      "comment": "国内最良心的免费模型，编程 / Agent 兜底首选",
      "url": "https://open.bigmodel.cn",
      "end": null,
      "forever": true
    },
    {
      "name": "hunyuan-lite",
      "vendor": "腾讯云混元",
      "cat": "api",
      "region": "cn",
      "desc": "lite 版模型永久免费",
      "limits": "RPM 并发配额，重任务需换更大杯",
      "card": false,
      "cardNote": "",
      "comment": "免费档里能打的长文本备胎",
      "url": "https://cloud.tencent.com/product/hunyuan",
      "end": null,
      "forever": true
    },
    {
      "name": "ERNIE Speed / Lite",
      "vendor": "百度千帆",
      "cat": "api",
      "region": "cn",
      "desc": "官方宣布永久免费的小杯模型",
      "limits": "RPM 配额限制，能力弱于旗舰",
      "card": false,
      "cardNote": "",
      "comment": "中文轻任务够用，新客另有体验金",
      "url": "https://cloud.baidu.com/product/qianfan",
      "end": null,
      "forever": true
    },
    {
      "name": "Spark Lite",
      "vendor": "讯飞星火",
      "cat": "api",
      "region": "cn",
      "desc": "Lite 版永久免费",
      "limits": "并发数较低，适合轻量调用",
      "card": false,
      "cardNote": "",
      "comment": "免费档里响应速度不错",
      "url": "https://www.xfyun.cn",
      "end": null,
      "forever": true
    },
    {
      "name": "免费模型池",
      "vendor": "硅基流动",
      "cat": "api",
      "region": "cn",
      "desc": "平台内多款小尺寸开源模型免费",
      "limits": "仅指定小模型，限 RPM / 每日额度",
      "card": false,
      "cardNote": "",
      "comment": "配合注册送的 2000 万 token，白嫖起步站",
      "url": "https://siliconflow.cn",
      "end": null,
      "forever": true
    },
    {
      "name": "Gemini 2.5 Flash 免费层",
      "vendor": "Google",
      "cat": "api",
      "region": "intl",
      "desc": "AI Studio 免费 RPM / 每日配额",
      "limits": "每分钟 / 每日请求数限额，免费层数据可能用于训练",
      "card": false,
      "cardNote": "",
      "comment": "国际免费层天花板，百万级上下文",
      "url": "https://aistudio.google.com",
      "end": null,
      "forever": true
    },
    {
      "name": "OpenRouter :free 模型",
      "vendor": "OpenRouter",
      "cat": "api",
      "region": "intl",
      "desc": "带 :free 后缀的模型每日免费请求",
      "limits": "未充值 50 次 / 日，充值 $10 后升 1000 次 / 日",
      "card": false,
      "cardNote": "",
      "comment": "一个 key 白嫖多家的免费版本",
      "url": "https://openrouter.ai",
      "end": null,
      "forever": true
    },
    {
      "name": "Groq 免费层",
      "vendor": "Groq",
      "cat": "api",
      "region": "intl",
      "desc": "主流开源模型免费限额调用",
      "limits": "RPM / RPD 限额，仅平台托管模型",
      "card": false,
      "cardNote": "",
      "comment": "LPU 推理速度极快，大批量轻任务神器",
      "url": "https://console.groq.com",
      "end": null,
      "forever": true
    },
    {
      "name": "Cerebras 免费层",
      "vendor": "Cerebras",
      "cat": "api",
      "region": "intl",
      "desc": "每日免费 token 配额",
      "limits": "每日 tokens 上限，仅托管的开源模型",
      "card": false,
      "cardNote": "",
      "comment": "推理速度竞速赛冠军常客",
      "url": "https://cloud.cerebras.ai",
      "end": null,
      "forever": true
    },
    {
      "name": "GitHub Models",
      "vendor": "GitHub",
      "cat": "api",
      "region": "intl",
      "desc": "免费试用 GPT / Claude / Llama 等各家模型",
      "limits": "按账号等级限速，不可用于生产",
      "card": "alt",
      "cardNote": "要 GitHub 账号",
      "comment": "一个 GitHub 账号试遍各家旗舰",
      "url": "https://github.com/marketplace/models",
      "end": null,
      "forever": true
    },
    {
      "name": "DeepSeek 对话版",
      "vendor": "深度求索",
      "cat": "web",
      "region": "cn",
      "desc": "网页 / App 基本无限量免费",
      "limits": "高峰期限流，功能比 API 版少",
      "card": false,
      "cardNote": "",
      "comment": "全场最像「真免费」的旗舰对话",
      "url": "https://chat.deepseek.com",
      "end": null,
      "forever": true
    },
    {
      "name": "Kimi",
      "vendor": "月之暗面",
      "cat": "web",
      "region": "cn",
      "desc": "网页 / App 免费使用",
      "limits": "高峰期限速，超长上下文有档位",
      "card": false,
      "cardNote": "",
      "comment": "长文档阅读免费首选",
      "url": "https://www.kimi.com",
      "end": null,
      "forever": true
    },
    {
      "name": "豆包",
      "vendor": "字节跳动",
      "cat": "web",
      "region": "cn",
      "desc": "App / 网页免费使用",
      "limits": "部分高级功能收费或限次",
      "card": false,
      "cardNote": "",
      "comment": "日常问答 / 语音全家桶免费给得大方",
      "url": "https://www.doubao.com",
      "end": null,
      "forever": true
    },
    {
      "name": "ChatGPT Free",
      "vendor": "OpenAI",
      "cat": "web",
      "region": "intl",
      "desc": "免费档可用旗舰模型",
      "limits": "消息数动态限额，超限降级小杯",
      "card": false,
      "cardNote": "",
      "comment": "国际对话基线，白嫖额度时紧时松",
      "url": "https://chatg.com",
      "end": null,
      "forever": true
    },
    {
      "name": "GitHub Copilot Free",
      "vendor": "GitHub",
      "cat": "code",
      "region": "intl",
      "desc": "每月 2000 次补全 + 50 次对话请求",
      "limits": "月额度用完等刷新，模型选择受限",
      "card": false,
      "cardNote": "",
      "comment": "白嫖 AI 编程补全的起点",
      "url": "https://github.com/features/copilot",
      "end": null,
      "forever": true
    },
    {
      "name": "通义灵码 标准版",
      "vendor": "阿里",
      "cat": "code",
      "region": "cn",
      "desc": "代码补全免费不限量",
      "limits": "高级模型 / 企业功能要专业版",
      "card": false,
      "cardNote": "",
      "comment": "国内 IDE 补全免费天花板",
      "url": "https://tongyi.aliyun.com/lingma",
      "end": null,
      "forever": true
    },
    {
      "name": "Cursor Hobby",
      "vendor": "Cursor",
      "cat": "code",
      "region": "intl",
      "desc": "有限补全与慢速请求额度",
      "limits": "月度额度小，高峰期排队",
      "card": false,
      "cardNote": "",
      "comment": "体验 AI IDE 的入门票",
      "url": "https://cursor.com",
      "end": null,
      "forever": true
    },
    {
      "name": "GLM-4.6 全量限时免费",
      "vendor": "智谱 AI",
      "cat": "promo",
      "region": "cn",
      "desc": "新模型上线限量期，API 全量免费开放",
      "limits": "每日限量请求，超量后恢复原价",
      "card": false,
      "cardNote": "",
      "comment": "新模型发布期的标准羊毛，手快有",
      "url": "https://open.bigmodel.cn",
      "end": "2026-09-03"
    },
    {
      "name": "Kimi K3 公测免费",
      "vendor": "月之暗面",
      "cat": "promo",
      "region": "cn",
      "desc": "K3 新模型 API 公测期免费调用",
      "limits": "公测期限速，并发 / 上下文受限",
      "card": false,
      "cardNote": "",
      "comment": "公测期白嫖旗舰，顺手测编程能力",
      "url": "https://platform.moonshot.cn",
      "end": "2026-09-20"
    },
    {
      "name": "Doubao-1.6 体验期免费",
      "vendor": "火山方舟",
      "cat": "promo",
      "region": "cn",
      "desc": "新模型体验期免费额度，安心体验模式 0 计费",
      "limits": "每模型 50 万 tokens 体验额度",
      "card": false,
      "cardNote": "",
      "comment": "配合每日 200 万签到，白嫖主力",
      "url": "https://www.volcengine.com/product/ark",
      "end": "2026-09-30"
    },
    {
      "name": "GLM Coding 新客首月 ¥1",
      "vendor": "智谱 AI",
      "cat": "promo",
      "region": "cn",
      "desc": "编程套餐首月 1 元体验",
      "limits": "仅新客首月，次月恢复原价可随时取消",
      "card": false,
      "cardNote": "",
      "comment": "1 块钱用满 GLM-4.7 编程额度",
      "url": "https://www.bigmodel.cn",
      "end": "2026-09-30"
    },
    {
      "name": "Trae IDE 旗舰模型免费",
      "vendor": "字节跳动",
      "cat": "promo",
      "region": "cn",
      "desc": "IDE 内活动期免费用旗舰模型",
      "limits": "活动期额度动态调整，可能有次数上限",
      "card": false,
      "cardNote": "",
      "comment": "活动期内的编程白嫖大额窗口",
      "url": "https://www.trae.ai",
      "end": "2026-10-31"
    },
    {
      "name": "Cursor Pro 试用",
      "vendor": "Cursor",
      "cat": "promo",
      "region": "intl",
      "desc": "Pro 完整功能两周免费试用",
      "limits": "注册起 14 天，到期自动扣费需手动取消",
      "card": "alt",
      "cardNote": "试用要绑卡，记得取消",
      "comment": "敢绑卡可白嫖两周完整 Pro",
      "url": "https://cursor.com",
      "end": null,
      "term": "注册起 14 天"
    }
  ],
  "plans": [
    {
      "vendor": "DeepSeek",
      "plan": "按量 API（无订阅）",
      "price": 0,
      "priceText": "按量",
      "cut": "",
      "model": "V3.2 / Reasoner",
      "quota": "无月费，充多少用多少，价格本身就是全场锚点",
      "tools": "任意 OpenAI 兼容客户端",
      "note": "0 门槛",
      "tag": "best",
      "region": "cn",
      "url": "https://platform.deepseek.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Lite",
      "price": 20,
      "priceText": "¥20",
      "cut": "首月常有新客特惠",
      "model": "GLM-4.7 高速版",
      "quota": "轻量编程用量，日常小项目够用",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "入门首选",
      "tag": "pop",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "通义灵码",
      "plan": "个人专业版",
      "price": 48,
      "priceText": "¥48",
      "cut": "",
      "model": "Qwen3 系列",
      "quota": "代码补全 + 智能体编程，IDE 深度集成",
      "tools": "VS Code / JetBrains",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://tongyi.aliyun.com/lingma"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Andante",
      "price": 49,
      "priceText": "¥49",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 300 次 / 5 小时窗口，周额度滚动刷新",
      "tools": "Claude Code / Kimi CLI",
      "note": "档位最细",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "MiniMax",
      "plan": "Coding 体验版",
      "price": 49,
      "priceText": "¥49",
      "cut": "",
      "model": "MiniMax M2 系列",
      "quota": "入门编程额度，M2 主打高 token 效率",
      "tools": "Claude Code / Cline",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.minimaxi.com"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Moderato",
      "price": 99,
      "priceText": "¥99",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 600 次 / 5 小时窗口，最高 100 tokens/s",
      "tools": "Claude Code / Kimi CLI",
      "note": "中度日用",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Pro",
      "price": 100,
      "priceText": "¥100",
      "cut": "",
      "model": "GLM-4.7 高速版",
      "quota": "Pro 级编程额度，窗口配额约为 Lite 数倍",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Allegretto",
      "price": 199,
      "priceText": "¥199",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 1000 次 / 5 小时窗口，并发更高",
      "tools": "Claude Code / Kimi CLI",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Max",
      "price": 200,
      "priceText": "¥200",
      "cut": "",
      "model": "GLM-4.7 高速版",
      "quota": "顶配窗口额度，重度整仓重构友好",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Allegro",
      "price": 699,
      "priceText": "¥699",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 1200 次 / 5 小时窗口，团队重度使用",
      "tools": "Claude Code / Kimi CLI",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "GitHub Copilot",
      "plan": "Copilot Pro",
      "price": 73,
      "priceText": "$10",
      "cut": "约 ¥73 / 月",
      "model": "多模型可选（GPT / Claude 等）",
      "quota": "每月 300 次高级请求 + 无限补全",
      "tools": "VS Code / JetBrains / CLI",
      "note": "老牌稳妥",
      "tag": "",
      "region": "intl",
      "url": "https://github.com/features/copilot"
    },
    {
      "vendor": "Anthropic",
      "plan": "Claude Pro",
      "price": 145,
      "priceText": "$20",
      "cut": "约 ¥145 / 月",
      "model": "Claude 最新 Sonnet 系列",
      "quota": "有限窗口内使用最新旗舰，编程质量标杆",
      "tools": "Claude Code / Claude App",
      "note": "质量锚点",
      "tag": "",
      "region": "intl",
      "url": "https://claude.com"
    },
    {
      "vendor": "OpenAI",
      "plan": "ChatGPT Plus",
      "price": 145,
      "priceText": "$20",
      "cut": "约 ¥145 / 月",
      "model": "GPT 旗舰系列",
      "quota": "通用对话 + 编程 + Agent，额度动态调整",
      "tools": "Codex / ChatGPT App",
      "note": "全能锚点",
      "tag": "",
      "region": "intl",
      "url": "https://chatg.com"
    }
  ],
  "models": [
    {
      "name": "DeepSeek-V3.2",
      "vendor": "深度求索",
      "ctx": 128,
      "pin": 2,
      "pout": 3,
      "region": "cn",
      "free": "无（但足够便宜）",
      "comment": "一线旗舰里最狠的价格，性价比基准线",
      "url": "https://platform.deepseek.com"
    },
    {
      "name": "GLM-4.7",
      "vendor": "智谱 AI",
      "ctx": 200,
      "pin": 4,
      "pout": 14,
      "region": "cn",
      "free": "Flash 系列永久免费",
      "comment": "Agent / 编程能力强，Flash 免费版可日常兜底",
      "url": "https://open.bigmodel.cn"
    },
    {
      "name": "Kimi-K2",
      "vendor": "月之暗面",
      "ctx": 256,
      "pin": 4,
      "pout": 17,
      "region": "cn",
      "free": "新客 ¥15 体验金",
      "comment": "长文本与 Agentic 任务强项，编程订阅更划算",
      "url": "https://platform.moonshot.cn"
    },
    {
      "name": "Qwen3-Max",
      "vendor": "阿里云",
      "ctx": 256,
      "pin": 6,
      "pout": 24,
      "region": "cn",
      "free": "新客每模型 100 万",
      "comment": "综合能力旗舰，百炼新客先白嫖再充值",
      "url": "https://bailian.console.aliyun.com"
    },
    {
      "name": "Doubao-Seed-1.6",
      "vendor": "字节 · 火山方舟",
      "ctx": 256,
      "pin": 0.8,
      "pout": 2.4,
      "region": "cn",
      "free": "每日可领 200 万",
      "comment": "价格屠夫，配合每日签到几乎不花钱",
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "name": "MiniMax-M2",
      "vendor": "MiniMax",
      "ctx": 200,
      "pin": 2,
      "pout": 8,
      "region": "cn",
      "free": "新客 ¥15 代金券",
      "comment": "主打高 token 效率，编程场景实际成本再打折",
      "url": "https://www.minimaxi.com"
    },
    {
      "name": "ERNIE-4.5-Turbo",
      "vendor": "百度",
      "ctx": 128,
      "pin": 0.8,
      "pout": 3.2,
      "region": "cn",
      "free": "新客每模型 100 万",
      "comment": "中文知识场景稳，千帆新客额度慢慢薅",
      "url": "https://cloud.baidu.com/product/qianfan"
    },
    {
      "name": "Gemini-2.5-Flash",
      "vendor": "Google",
      "ctx": 1000,
      "pin": 2.2,
      "pout": 18,
      "region": "intl",
      "free": "免费层每日配额",
      "comment": "免费层最香的旗舰 Flash，百万级上下文",
      "url": "https://aistudio.google.com"
    },
    {
      "name": "GPT-5",
      "vendor": "OpenAI",
      "ctx": 400,
      "pin": 9,
      "pout": 72,
      "region": "intl",
      "free": "无",
      "comment": "国际旗舰锚点，国内平替价格约为 1/10",
      "url": "https://openai.com"
    }
  ],
  "checkedAt": "2026-09-05"
};
