/* ================================================================
 * AI 厂商福利情报站 · 数据文件（由人工与 scripts/update-data.mjs 共同维护）
 * 自动收录的条目带 "auto": true，人工核对无误后请删掉该标记。
 * ================================================================ */
window.DATA = {
  "updatedAt": "2026-09-01",
  "eggs": [
    {
      "vendor": "智谱 AI",
      "color": "#4f6ef7",
      "title": "新用户注册礼",
      "desc": "注册即送 2000 万 Tokens，GLM 全系模型通用，标注为永久额度",
      "amount": "2000 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 2000,
      "forever": true,
      "end": null,
      "url": "https://open.bigmodel.cn"
    },
    {
      "vendor": "智谱 AI",
      "color": "#4f6ef7",
      "title": "GLM-Flash 系列",
      "desc": "GLM-4-Flash / 4.7-Flash 开放平台永久免费，仅限并发数",
      "amount": "0 元",
      "unit": "长期免费",
      "type": "forever",
      "value": 2400,
      "forever": true,
      "end": null,
      "url": "https://open.bigmodel.cn"
    },
    {
      "vendor": "硅基流动",
      "color": "#7c5cff",
      "title": "新用户注册礼",
      "desc": "注册送 2000 万 Tokens 永久额度，平台聚合 DeepSeek / Qwen / GLM 等热门开源模型",
      "amount": "2000 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 2000,
      "forever": true,
      "end": null,
      "url": "https://siliconflow.cn"
    },
    {
      "vendor": "阿里云百炼",
      "color": "#ff6a00",
      "title": "新客全家桶",
      "desc": "新用户每个模型 100 万 Tokens，覆盖 Qwen / DeepSeek / Kimi 等 100+ 模型",
      "amount": "100 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 800,
      "end": "2026-11-30",
      "url": "https://bailian.console.aliyun.com"
    },
    {
      "vendor": "火山方舟",
      "color": "#3b82f6",
      "title": "协作奖励计划",
      "desc": "加入计划后每天可领 200 万 Tokens，长期有效，豆包 / DeepSeek / Qwen 全系可用",
      "amount": "200 万",
      "unit": "每天",
      "type": "daily",
      "value": 1200,
      "forever": true,
      "end": null,
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "vendor": "火山方舟",
      "color": "#3b82f6",
      "title": "新模型体验额度",
      "desc": "每个模型免费 50 万 tokens 体验金，安心体验模式下不计费",
      "amount": "50 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 300,
      "end": "2026-11-15",
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "vendor": "DeepSeek",
      "color": "#4d6bfe",
      "title": "V3.2 上线限时 5 折",
      "desc": "新版本 API 限时半价，输入 ¥1 / 输出 ¥1.5 每百万 tokens",
      "amount": "5 折",
      "unit": "API 折扣",
      "type": "limited",
      "value": 600,
      "end": "2026-09-03",
      "url": "https://platform.deepseek.com"
    },
    {
      "vendor": "腾讯云混元",
      "color": "#0052d9",
      "title": "新客体验金",
      "desc": "新用户 100 万 Tokens，有效期一年，混元全系模型可用",
      "amount": "100 万",
      "unit": "Tokens",
      "type": "signup",
      "value": 100,
      "end": "2026-12-31",
      "url": "https://cloud.tencent.com/product/hunyuan"
    },
    {
      "vendor": "百度千帆",
      "color": "#2932e1",
      "title": "新客模型体验金",
      "desc": "每个模型 100 万 Tokens 免费额度，ERNIE 系列与开源模型均可体验",
      "amount": "100 万",
      "unit": "× 每模型",
      "type": "signup",
      "value": 100,
      "end": "2026-10-31",
      "url": "https://cloud.baidu.com/product/qianfan"
    },
    {
      "vendor": "Moonshot Kimi",
      "color": "#000000",
      "title": "开放平台新客券",
      "desc": "注册送 15 元体验金，K2 系列模型 API 通用，可抵扣按量费用",
      "amount": "¥15",
      "unit": "代金券",
      "type": "signup",
      "value": 400,
      "end": "2026-09-15",
      "url": "https://platform.moonshot.cn"
    },
    {
      "vendor": "MiniMax",
      "color": "#f23f5d",
      "title": "新客代金券包",
      "desc": "注册送 15 元代金券，M2 系列 API 通用，另有免费体验模型",
      "amount": "¥15",
      "unit": "代金券",
      "type": "signup",
      "value": 400,
      "end": "2026-09-30",
      "url": "https://www.minimaxi.com"
    },
    {
      "vendor": "Google Gemini",
      "color": "#1a73e8",
      "title": "API 免费层",
      "desc": "Flash 系列免费层每分钟 / 每日均有免费请求配额，个人开发够用",
      "amount": "免费层",
      "unit": "每日配额",
      "type": "forever",
      "value": 1500,
      "forever": true,
      "end": null,
      "url": "https://aistudio.google.com"
    },
    {
      "vendor": "OpenRouter",
      "color": "#a3a3a3",
      "title": ":free 模型通道",
      "desc": "带 :free 后缀的模型每日 50 次免费请求，聚合多家厂商的免费版本",
      "amount": "50 次",
      "unit": "每天",
      "type": "daily",
      "value": 200,
      "forever": true,
      "end": null,
      "url": "https://openrouter.ai"
    },
    {
      "vendor": "Groq",
      "color": "#f55036",
      "title": "免费层极速推理",
      "desc": "开源模型免费层每日可用，LPU 推理速度极快，适合大批量轻任务",
      "amount": "每日",
      "unit": "免费配额",
      "type": "daily",
      "value": 150,
      "forever": true,
      "end": null,
      "url": "https://console.groq.com"
    }
  ],
  "plans": [
    {
      "vendor": "DeepSeek",
      "plan": "按量 API（无订阅）",
      "price": 0,
      "priceText": "按量",
      "cut": "",
      "model": "V3.2 / Reasoner",
      "quota": "无月费，充多少用多少，价格本身就是全场锚点",
      "tools": "任意 OpenAI 兼容客户端",
      "note": "0 门槛",
      "tag": "best",
      "region": "cn",
      "url": "https://platform.deepseek.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Lite",
      "price": 20,
      "priceText": "¥20",
      "cut": "首月常有新客特惠",
      "model": "GLM-4.7 高速版",
      "quota": "轻量编程用量，日常小项目够用",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "入门首选",
      "tag": "pop",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "通义灵码",
      "plan": "个人专业版",
      "price": 48,
      "priceText": "¥48",
      "cut": "",
      "model": "Qwen3 系列",
      "quota": "代码补全 + 智能体编程，IDE 深度集成",
      "tools": "VS Code / JetBrains",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://tongyi.aliyun.com/lingma"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Andante",
      "price": 49,
      "priceText": "¥49",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 300 次 / 5 小时窗口，周额度滚动刷新",
      "tools": "Claude Code / Kimi CLI",
      "note": "档位最细",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "MiniMax",
      "plan": "Coding 体验版",
      "price": 49,
      "priceText": "¥49",
      "cut": "",
      "model": "MiniMax M2 系列",
      "quota": "入门编程额度，M2 主打高 token 效率",
      "tools": "Claude Code / Cline",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.minimaxi.com"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Moderato",
      "price": 99,
      "priceText": "¥99",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 600 次 / 5 小时窗口，最高 100 tokens/s",
      "tools": "Claude Code / Kimi CLI",
      "note": "中度日用",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Pro",
      "price": 100,
      "priceText": "¥100",
      "cut": "",
      "model": "GLM-4.7 高速版",
      "quota": "Pro 级编程额度，窗口配额约为 Lite 数倍",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Allegretto",
      "price": 199,
      "priceText": "¥199",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 1000 次 / 5 小时窗口，并发更高",
      "tools": "Claude Code / Kimi CLI",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "智谱 AI",
      "plan": "GLM Coding Max",
      "price": 200,
      "priceText": "¥200",
      "cut": "",
      "model": "GLM-4.7 高速版",
      "quota": "顶配窗口额度，重度整仓重构友好",
      "tools": "Claude Code / Cline / Roo Code",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.bigmodel.cn"
    },
    {
      "vendor": "Kimi",
      "plan": "Coding · Allegro",
      "price": 699,
      "priceText": "¥699",
      "cut": "",
      "model": "Kimi K 系列",
      "quota": "约 1200 次 / 5 小时窗口，团队重度使用",
      "tools": "Claude Code / Kimi CLI",
      "note": "",
      "tag": "",
      "region": "cn",
      "url": "https://www.kimi.com"
    },
    {
      "vendor": "GitHub Copilot",
      "plan": "Copilot Pro",
      "price": 73,
      "priceText": "$10",
      "cut": "约 ¥73 / 月",
      "model": "多模型可选（GPT / Claude 等）",
      "quota": "每月 300 次高级请求 + 无限补全",
      "tools": "VS Code / JetBrains / CLI",
      "note": "老牌稳妥",
      "tag": "",
      "region": "intl",
      "url": "https://github.com/features/copilot"
    },
    {
      "vendor": "Anthropic",
      "plan": "Claude Pro",
      "price": 145,
      "priceText": "$20",
      "cut": "约 ¥145 / 月",
      "model": "Claude 最新 Sonnet 系列",
      "quota": "有限窗口内使用最新旗舰，编程质量标杆",
      "tools": "Claude Code / Claude App",
      "note": "质量锚点",
      "tag": "",
      "region": "intl",
      "url": "https://claude.com"
    },
    {
      "vendor": "OpenAI",
      "plan": "ChatGPT Plus",
      "price": 145,
      "priceText": "$20",
      "cut": "约 ¥145 / 月",
      "model": "GPT 旗舰系列",
      "quota": "通用对话 + 编程 + Agent，额度动态调整",
      "tools": "Codex / ChatGPT App",
      "note": "全能锚点",
      "tag": "",
      "region": "intl",
      "url": "https://chatg.com"
    }
  ],
  "models": [
    {
      "name": "DeepSeek-V3.2",
      "vendor": "深度求索",
      "ctx": 128,
      "pin": 2,
      "pout": 3,
      "region": "cn",
      "free": "无（但足够便宜）",
      "comment": "一线旗舰里最狠的价格，性价比基准线",
      "url": "https://platform.deepseek.com"
    },
    {
      "name": "GLM-4.7",
      "vendor": "智谱 AI",
      "ctx": 200,
      "pin": 4,
      "pout": 14,
      "region": "cn",
      "free": "Flash 系列永久免费",
      "comment": "Agent / 编程能力强，Flash 免费版可日常兜底",
      "url": "https://open.bigmodel.cn"
    },
    {
      "name": "Kimi-K2",
      "vendor": "月之暗面",
      "ctx": 256,
      "pin": 4,
      "pout": 17,
      "region": "cn",
      "free": "新客 ¥15 体验金",
      "comment": "长文本与 Agentic 任务强项，编程订阅更划算",
      "url": "https://platform.moonshot.cn"
    },
    {
      "name": "Qwen3-Max",
      "vendor": "阿里云",
      "ctx": 256,
      "pin": 6,
      "pout": 24,
      "region": "cn",
      "free": "新客每模型 100 万",
      "comment": "综合能力旗舰，百炼新客先白嫖再充值",
      "url": "https://bailian.console.aliyun.com"
    },
    {
      "name": "Doubao-Seed-1.6",
      "vendor": "字节 · 火山方舟",
      "ctx": 256,
      "pin": 0.8,
      "pout": 2.4,
      "region": "cn",
      "free": "每日可领 200 万",
      "comment": "价格屠夫，配合每日签到几乎不花钱",
      "url": "https://www.volcengine.com/product/ark"
    },
    {
      "name": "MiniMax-M2",
      "vendor": "MiniMax",
      "ctx": 200,
      "pin": 2,
      "pout": 8,
      "region": "cn",
      "free": "新客 ¥15 代金券",
      "comment": "主打高 token 效率，编程场景实际成本再打折",
      "url": "https://www.minimaxi.com"
    },
    {
      "name": "ERNIE-4.5-Turbo",
      "vendor": "百度",
      "ctx": 128,
      "pin": 0.8,
      "pout": 3.2,
      "region": "cn",
      "free": "新客每模型 100 万",
      "comment": "中文知识场景稳，千帆新客额度慢慢薅",
      "url": "https://cloud.baidu.com/product/qianfan"
    },
    {
      "name": "Gemini-2.5-Flash",
      "vendor": "Google",
      "ctx": 1000,
      "pin": 2.2,
      "pout": 18,
      "region": "intl",
      "free": "免费层每日配额",
      "comment": "免费层最香的旗舰 Flash，百万级上下文",
      "url": "https://aistudio.google.com"
    },
    {
      "name": "GPT-5",
      "vendor": "OpenAI",
      "ctx": 400,
      "pin": 9,
      "pout": 72,
      "region": "intl",
      "free": "无",
      "comment": "国际旗舰锚点，国内平替价格约为 1/10",
      "url": "https://openai.com"
    }
  ],
  "checkedAt": "2026-09-01"
};
